#!/bin/bash

if [ "$(id -u)" != 0 ]; then
    echo "You're not root! Run script with sudo" && exit 1
fi

set -euo pipefail
exec 2> >(tee "error_log_$(date -Iseconds).txt")

GREEN=$(tput setaf 2)
BOLD=$(tput bold)
RESET=$(tput sgr0)

source /etc/os-release

common_packages_to_remove=(
    cheese
    gedit
    rhythmbox
    totem)

common_packages_to_install=(
    ImageMagick
    borgbackup
    chromium
    code
    ffmpeg
    fuse-exfat
    gcc-c++
    gh
    gnome-shell-extension-auto-move-windows
    gnome-tweaks
    keepassxc
    libva-intel-driver
    mediainfo
    mpv
    nodejs
    optipng
    podman
    podman-docker
    stow
    thunderbird
    transmission-gtk
    v4l2loopback
    xclip)

common_flathub_packages_to_install=(
    fr.handbrake.ghb
    org.kde.krita
    org.signal.Signal)

#==============================================================================
# For RHEL 8 and clones
#==============================================================================
if [[ ("$ID" == "centos" || "$ID" == "rocky") && "$VERSION_ID" == 8 ]]; then
    rhel_packages_to_remove=(
        evolution
        firefox
        pidgin)

    rhel_packages_to_install=(
        ntfs-3g
        python36-devel)

    rhel_flathub_packages_to_install=(
        org.mozilla.firefox
        org.gnome.Shotwell
        org.bunkus.mkvtoolnix-gui)

    echo "${BOLD}Installing binaries for RHEL clones not available in repositories...${RESET}"
    curl -LOf https://github.com/jgm/pandoc/releases/download/2.11.2/pandoc-2.11.2-linux-amd64.tar.gz
    echo "9d265941f224d376514e18fc45d5292e9c2481b04693c96917a0d55ed817b190cf2ea2666097388bfdf30023db2628567ea04ff6b9cc3316130a8190da72c605 ./pandoc-2.11.2-linux-amd64.tar.gz" |
        sha512sum --check
    tar -C /usr/local/bin/ -xf pandoc-2.11.2-linux-amd64.tar.gz --no-anchored 'pandoc' --strip=2

    curl -LOf https://github.com/koalaman/shellcheck/releases/download/v0.7.1/shellcheck-v0.7.1.linux.x86_64.tar.xz
    echo "beca3d7819a6bdcfbd044576df4fc284053b48f468b2f03428fe66f4ceb2c05d9b5411357fa15003cb0311406c255084cf7283a3b8fce644c340c2f6aa910b9f ./shellcheck-v0.7.1.linux.x86_64.tar.xz" |
        sha512sum --check
    tar -C /usr/local/bin/ -xf shellcheck-v0.7.1.linux.x86_64.tar.xz --no-anchored 'shellcheck' --strip=1

    curl -LOf https://github.com/mvdan/sh/releases/download/v3.2.2/shfmt_v3.2.2_linux_amd64
    echo "d4e699575899f7c44dbce54f6414fb63c0527e7d743ea724cb0091417e07a353c1d156d4184580a260ca855cdf5e01cdf46b353f04cf5093eba3ffc02223f1c6 ./shfmt_v3.2.2_linux_amd64" |
        sha512sum --check
    chmod +x shfmt_v3.2.2_linux_amd64
    mv shfmt_v3.2.2_linux_amd64 /usr/local/bin/shfmt

    dnf module enable -y nodejs:14

    common_packages_to_remove+=("${rhel_packages_to_remove[@]}")
    common_packages_to_install+=("${rhel_packages_to_install[@]}")
    common_flathub_packages_to_install+=("${rhel_flathub_packages_to_install[@]}")

    dnf -y config-manager --enable powertools
    dnf -y install epel-release
    dnf -y install --nogpgcheck https://download1.rpmfusion.org/free/el/rpmfusion-free-release-8.noarch.rpm https://download1.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-8.noarch.rpm

    #==============================================================================
    # For Fedora (tested on 34)
    #==============================================================================
elif [ "$ID" == "fedora" ]; then
    fedora_packages_to_remove=(
        gnome-photos)

    fedora_packages_to_install=(
        ShellCheck
        chromium-libs-media-freeworld
        java-1.8.0-openjdk
        lshw
        mkvtoolnix-gui
        pandoc
        shfmt
        shotwell
        zathura
        zathura-bash-completion
        zathura-pdf-mupdf)

    common_packages_to_remove+=("${fedora_packages_to_remove[@]}")
    common_packages_to_install+=("${fedora_packages_to_install[@]}")

    dnf -y install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

#==============================================================================
# For Unsupported OS / RHEL or clone version <8
#==============================================================================
else
    echo "Unsupported OS or version" && exit 1
fi

#==============================================================================
# Display user settings
#==============================================================================
clear
cat <<EOL
$ID $VERSION_ID detected

${BOLD}Packages to remove${RESET}
${BOLD}------------------${RESET}
RPM: ${GREEN}${common_packages_to_remove[*]}${RESET}

${BOLD}Packages to install${RESET}
${BOLD}-------------------${RESET}
RPM: ${GREEN}${common_packages_to_install[*]}${RESET}

Flathub: ${GREEN}${common_flathub_packages_to_install[*]}${RESET}

EOL
read -rp "Press enter to install, or ctrl+c to quit"

#==============================================================================
# Add common repositories
#==============================================================================
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

# note the spaces to make sure something like 'notnode' could not trigger 'nodejs' using [*]
case " ${common_packages_to_install[*]} " in
*' code '*)
    rpm --import https://packages.microsoft.com/keys/microsoft.asc
    sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'
    ;;&
*' gh '*)
    dnf -y config-manager --add-repo https://cli.github.com/packages/rpm/gh-cli.repo
    ;;
esac

#==============================================================================
# Install
#==============================================================================
echo "${BOLD}Removing unwanted programs...${RESET}"
dnf -y remove "${common_packages_to_remove[@]}"

echo "${BOLD}Updating...${RESET}"
dnf -y --refresh upgrade

echo "${BOLD}Installing packages...${RESET}"
dnf -y install "${common_packages_to_install[@]}"

echo "${BOLD}Installing flathub packages...${RESET}"
flatpak install -y flathub "${common_flathub_packages_to_install[@]}"
flatpak uninstall -y --unused

echo "${BOLD}Installing Deno...${RESET}"
/usr/bin/su - "$SUDO_USER" -c "curl -fsSL https://deno.land/x/install/install.sh | sh"

cat <<EOL
=============================================================================
Congratulations, everything is installed!

For RHEL clones, sudo dnf install ./abattis-cantarell-fonts-0.111-2.fc30.noarch.rpm to upgrade 0.0.25
pip3 install --user youtube-dl trash-cli tldr

You can set software to open in a certain workspace with:
gsettings set org.gnome.shell.extensions.auto-move-windows application-list "['thunderbird.desktop:2','org.signal.Signal.desktop:2']"

Now use the setup script...
=============================================================================
EOL
